[workspace]
members = [
  "crates/dsp-core",
  "crates/dsp-wasm",
  "crates/dsp-standalone",
  "crates/dsp-plugin",
  "src-tauri",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = "symbols"
